-- Operational source tables captured by Flink CDC.
-- The backing Postgres schema is defined in sql/source_postgres_schema.sql.

CREATE TABLE IF NOT EXISTS src_llm_request_events (
    request_id STRING,
    trace_id STRING,
    run_id STRING,
    span_id STRING,
    agent_id STRING,
    agent_name STRING,
    channel STRING,
    user_id STRING,
    session_id STRING,
    conversation_id STRING,
    app_name STRING,
    feature_name STRING,
    prompt_category STRING,
    prompt_id STRING,
    prompt_version STRING,
    model_name STRING,
    provider STRING,
    prompt_text STRING,
    response_text STRING,
    prompt_hash STRING,
    response_hash STRING,
    input_chars INT,
    output_chars INT,
    prompt_tokens INT,
    completion_tokens INT,
    total_tokens INT,
    request_type STRING,
    is_streaming BOOLEAN,
    temperature DOUBLE,
    max_tokens INT,
    finish_reason STRING,
    retry_count INT,
    latency_ms INT,
    status STRING,
    error_type STRING,
    http_status INT,
    estimated_cost_usd DOUBLE,
    mode STRING,
    region STRING,
    environment STRING,
    created_at TIMESTAMP(3),
    `date` DATE,
    PRIMARY KEY (request_id) NOT ENFORCED
) WITH (
    'connector' = 'postgres-cdc',
    'hostname' = 'postgres',
    'port' = '5432',
    'username' = 'ai_observability',
    'password' = 'ai_observability',
    'database-name' = 'ai_observability',
    'schema-name' = 'public',
    'table-name' = 'llm_request_events',
    'slot.name' = 'flink_llm_request_events_v5',
    'decoding.plugin.name' = 'pgoutput'
);
