-- Kafka ODS buffers CDC events before they are transformed into Paimon DWD/ADS.

CREATE TABLE IF NOT EXISTS kafka_ods_llm_request_events (
    request_id STRING,
    trace_id STRING,
    run_id STRING,
    span_id STRING,
    agent_id STRING,
    agent_name STRING,
    channel STRING,
    user_id STRING,
    session_id STRING,
    conversation_id STRING,
    app_name STRING,
    feature_name STRING,
    prompt_category STRING,
    prompt_id STRING,
    prompt_version STRING,
    model_name STRING,
    provider STRING,
    prompt_text STRING,
    response_text STRING,
    prompt_hash STRING,
    response_hash STRING,
    input_chars INT,
    output_chars INT,
    prompt_tokens INT,
    completion_tokens INT,
    total_tokens INT,
    request_type STRING,
    is_streaming BOOLEAN,
    temperature DOUBLE,
    max_tokens INT,
    finish_reason STRING,
    retry_count INT,
    latency_ms INT,
    status STRING,
    error_type STRING,
    http_status INT,
    estimated_cost_usd DOUBLE,
    mode STRING,
    region STRING,
    environment STRING,
    created_at TIMESTAMP(3),
    `date` DATE,
    PRIMARY KEY (request_id) NOT ENFORCED
) WITH (
    'connector' = 'upsert-kafka',
    'topic' = 'ods_llm_request_events',
    'properties.bootstrap.servers' = 'kafka:9092',
    'properties.group.id' = 'flink-ods-llm-request-events',
    'key.format' = 'json',
    'value.format' = 'json',
    'value.json.fail-on-missing-field' = 'false',
    'value.json.ignore-parse-errors' = 'true'
);
