-- Stream CDC changes into Kafka ODS.

INSERT INTO kafka_ods_llm_request_events
SELECT
    request_id,
    trace_id,
    run_id,
    span_id,
    agent_id,
    agent_name,
    channel,
    user_id,
    session_id,
    conversation_id,
    app_name,
    feature_name,
    prompt_category,
    prompt_id,
    prompt_version,
    model_name,
    provider,
    prompt_text,
    response_text,
    prompt_hash,
    response_hash,
    input_chars,
    output_chars,
    prompt_tokens,
    completion_tokens,
    total_tokens,
    request_type,
    is_streaming,
    temperature,
    max_tokens,
    finish_reason,
    retry_count,
    latency_ms,
    status,
    error_type,
    http_status,
    estimated_cost_usd,
    mode,
    region,
    environment,
    created_at,
    `date`
FROM src_llm_request_events;
