TRUNCATE TABLE ai_observability.dws_ai_llm_feature_request_1d;
TRUNCATE TABLE ai_observability.dws_ai_retrieval_knowledge_base_request_1d;
TRUNCATE TABLE ai_observability.dws_ai_feedback_feature_action_1d;
TRUNCATE TABLE ai_observability.dws_ai_guardrail_rule_check_1d;
TRUNCATE TABLE ai_observability.dws_ai_cost_team_request_1d;
TRUNCATE TABLE ai_observability.dws_ai_evaluation_feature_judgment_1d;

INSERT INTO ai_observability.dws_ai_llm_feature_request_1d
SELECT *
FROM paimon_lake.dws.dws_ai_llm_feature_request_1d;

INSERT INTO ai_observability.dws_ai_retrieval_knowledge_base_request_1d
SELECT *
FROM paimon_lake.dws.dws_ai_retrieval_knowledge_base_request_1d;

INSERT INTO ai_observability.dws_ai_feedback_feature_action_1d
SELECT *
FROM paimon_lake.dws.dws_ai_feedback_feature_action_1d;

INSERT INTO ai_observability.dws_ai_guardrail_rule_check_1d
SELECT *
FROM paimon_lake.dws.dws_ai_guardrail_rule_check_1d;

INSERT INTO ai_observability.dws_ai_cost_team_request_1d
SELECT *
FROM paimon_lake.dws.dws_ai_cost_team_request_1d;

INSERT INTO ai_observability.dws_ai_evaluation_feature_judgment_1d
SELECT *
FROM paimon_lake.dws.dws_ai_evaluation_feature_judgment_1d;
